### ISSUE TITLE
Making a Tourism website along with the booking page.

### ISSUE THREAD

**Issue by samiksha-prog** [ows-web/hacktoberfest22#98]
These are the following things I have to add:

Tourism.html : It contains the images, videos, callout, link to booking page, etc. about the tourist places.
tour.css : to style the Tourism.html file.
booking.html: For booking of the tour to the tourist place.
All the images and videos required.

**Comment by SonuKumar81800** [comment]
@samiksha-prog will you be one favour.

can you confirm me if this repository is excluded from hacktoberfest 22 or not.

**Comment by samiksha-prog** [comment]
It is included for hacktoberfest22, it should be considered as a
contribution in the hacktoberfest.
Thank you.

**Comment by samiksha-prog** [comment]
Sir, 
I have added a PR for this issue.
